export const buildingData = {
    name: 'Usine',
    floors: [
        {
            name: 'RDC',
            rooms: [
                { name: '1-Condensateur', occupied: false },
                { name: '2-Transfo futur', occupied: false },
                { name: '4-Local électrique', occupied: false },
                { name: '5-Local', occupied: true },
                { name: '6-Local électrique', occupied: true },
                { name: '7-Local', occupied: false },
                { name: '8-Stock' },
                { name: '12-Local Eaux', occupied: false },
                { name: '13-SAS', occupied: false },
                { name: '14-Entrepôt' },
                { name: '16-Local technique', occupied: false },
                { name: '18-Bureau', occupied: false },
                { name: '20-Local technique', occupied: true },
                { name: '21-Salle de pause', occupied: false },
                { name: '22-Accueil', occupied: false },
                { name: '23-Circulation', occupied: false },
                { name: '24-WC', occupied: true },
                { name: '25-WC', occupied: false },
                { name: '26-DGT', occupied: false },
                { name: '27-Vestiaire', occupied: false },
                { name: '28-Vestiaire', occupied: true },
                { name: '34-Local technique', occupied: true },
                { name: '35-Processus A', occupied: true },
                { name: '36-Processus B', occupied: true },
                { name: '37-Processus C' },
                { name: '39-Bureau', occupied: false },
                { name: '40-SAS', occupied: false },
                { name: '42-Local info', occupied: false },
                { name: '49-Rue centrale', occupied: false },
                { name: '52-Annexe chaufferie', occupied: false },
                { name: '57-Local technique', occupied: false },
                { name: '58-Pièce', occupied: false },
                { name: '59-Pièce', occupied: false },
                { name: '60-Pièce', occupied: false },
                { name: '61-Pièce', occupied: false },
                { name: '62-Pièce', occupied: false },
                { name: '63-Pièce', occupied: false },
                { name: '64-Pièce', occupied: false },
                { name: '65-Pièce', occupied: false },
                { name: '66-Pièce', occupied: false },
                { name: '67-Pièce', occupied: true },
                { name: '68-Pièce', occupied: false },
                { name: '69-Pièce', occupied: false },
                { name: '70-Pièce', occupied: false },
                { name: '71-Pièce', occupied: false },
                { name: '72-Pièce' },
                { name: '73-Pièce' },
                { name: '78-Pièce', occupied: false },
                { name: '79-Pièce', occupied: false },
                { name: '81-Pièce', occupied: false },
                { name: '82-Pièce', occupied: false },
                { name: '83-Pièce', occupied: false },
                { name: '84-Pièce', occupied: false },
                { name: '85-Pièce', occupied: false },
                { name: '86-Pièce', occupied: false },
                { name: '87-Pièce', occupied: false },
                { name: '88-Pièce', occupied: false },
            ],
        },
        {
            name: 'Toiture',
            rooms: [
                { name: '74-Pièce', occupied: false },
                { name: '75-Pièce', occupied: true },
                { name: '76-Pièce', occupied: true },
                { name: '77-Pièce' },
            ],
        },
        {
            name: 'Etage 1',
            rooms: [
                { name: '1-Condensateur', occupied: false },
            ],
        },
    ],
};
